# Copyright (C) 2013 The Android Open Source Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/amazon/tate/setup-makefiles.sh

PRODUCT_COPY_FILES += \
    vendor/amazon/soho/proprietary/etc/wifi/bcmdhd.cal:system/etc/wifi/bcmdhd.cal \
    vendor/amazon/soho/proprietary/vendor/firmware/ducati-m3-core0.xem3:system/vendor/firmware/ducati-m3-core0.xem3 \
    vendor/amazon/soho/proprietary/vendor/firmware/fw_bcm4330_apsta.bin:system/vendor/firmware/fw_bcm4330_apsta.bin \
    vendor/amazon/soho/proprietary/vendor/firmware/fw_bcm4330_p2p.bin:system/vendor/firmware/fw_bcm4330_p2p.bin \
    vendor/amazon/soho/proprietary/vendor/firmware/fw_bcm4330.bin:system/vendor/firmware/fw_bcm4330.bin \
    vendor/amazon/soho/proprietary/vendor/firmware/BCM4330B1_SOHO.HCD:system/vendor/firmware/BCM4330B1_SOHO.HCD \
    vendor/amazon/soho/proprietary/vendor/lib/libglslcompiler.so:system/vendor/lib/libglslcompiler.so \
    vendor/amazon/soho/proprietary/vendor/lib/libIMGegl.so:system/vendor/lib/libIMGegl.so \
    vendor/amazon/soho/proprietary/vendor/lib/libpvr2d.so:system/vendor/lib/libpvr2d.so \
    vendor/amazon/soho/proprietary/vendor/lib/libsmapi.so:system/vendor/lib/libsmapi.so \
    vendor/amazon/soho/proprietary/vendor/lib/libsrv_init.so:system/vendor/lib/libsrv_init.so \
    vendor/amazon/soho/proprietary/vendor/lib/libsrv_um.so:system/vendor/lib/libsrv_um.so \
    vendor/amazon/soho/proprietary/vendor/lib/libstagefright_soft_ddpdec.so:system/vendor/lib/libstagefright_soft_ddpdec.so \
    vendor/amazon/soho/proprietary/vendor/lib/libtf_crypto_sst.so:system/vendor/lib/libtf_crypto_sst.so \
    vendor/amazon/soho/proprietary/vendor/lib/libusc.so:system/vendor/lib/libusc.so \

